In [1]:
import numpy as np

In [ ]:
file = "eg.txt"
calls = []
with open(file) as f:
    first_line = f.readline()
    for i in first_line.strip().split(','):
        calls.append(int(i))
    # print(calls)

a = np.loadtxt(file, dtype = int, skiprows = 1)
n = np.shape(a)[0]//5
boards = np.reshape(a, (n,5,5))
rows = np.zeros((n,5), dtype = int)
cols = np.zeros((n,5), dtype = int)
rolling_sum = np.zeros((n), dtype = int)

for call in calls:
        locs = np.nonzero(boards == call)
        rolling_sum[locs[0]] += call
        rows[locs[0],locs[1]] +=1
        cols[locs[0], locs[2]] +=1
        if np.amax(rows) == 5:
            winner =np.unravel_index(rows.argmax(), rows.shape)[0]
            break
        if np.amax(cols) == 5:
            winner =np.unravel_index(cols.argmax(), cols.shape)[0]
            break

board_score = boards[winner].sum()-rolling_sum[winner]
print("board score", board_score)
print("last call", call)
print("score", board_score * call)

In [ ]:
import numpy as np
# pt 1
file = "input.txt"
calls = []
with open(file) as f:
    first_line = f.readline()
    for i in first_line.strip().split(','):
        calls.append(int(i))
    # print(calls)

a = np.loadtxt(file, dtype = int, skiprows = 1)
n = np.shape(a)[0]//5
boards = np.reshape(a, (n,5,5))
rows = np.zeros((n,5), dtype = int)
cols = np.zeros((n,5), dtype = int)
rolling_sum = np.zeros((n), dtype = int)

for call in calls:
        locs = np.nonzero(boards == call)
        rolling_sum[locs[0]] += call
        rows[locs[0],locs[1]] +=1
        cols[locs[0], locs[2]] +=1
        if np.amax(rows) == 5:
            winner =np.unravel_index(rows.argmax(), rows.shape)[0]
            break
        if np.amax(cols) == 5:
            winner =np.unravel_index(cols.argmax(), cols.shape)[0]
            break

board_score = boards[winner].sum()-rolling_sum[winner]
print("board score", board_score)
print("last call", call)
print("score", board_score * call)

In [ ]:
# pt 2
file = "eg.txt"
calls = []
with open(file) as f:
    first_line = f.readline()
    for i in first_line.strip().split(','):
        calls.append(int(i))

a = np.loadtxt(file, dtype = int, skiprows = 1)
n = np.shape(a)[0]//5
boards = np.reshape(a, (n,5,5))
rows = np.zeros((n,5), dtype = int)
cols = np.zeros((n,5), dtype = int)
rolling_sum = np.zeros((n), dtype = int)
winners = np.zeros((n), dtype = int)

for call in calls:
        locs = np.nonzero(boards == call)
        rolling_sum[locs[0]] += call
        rows[locs[0],locs[1]] +=1
        cols[locs[0], locs[2]] +=1
        if np.amax(rows) == 5:
            winners[np.unravel_index(rows.argmax(), rows.shape)[0]] =1
        if np.amax(cols) == 5:
            winners[np.unravel_index(cols.argmax(), cols.shape)[0]] =1
        if (n-sum(winners) ==1):
            break
loser = winners.argmin()
print(loser)
# board_score = boards[winner].sum()-rolling_sum[winner]
# print("board score", board_score)
# print("last call", call)
# print("score", board_score * call)

In [10]:
# pt 2
file = "input.txt"
calls = []
with open(file) as f:
    first_line = f.readline()
    for i in first_line.strip().split(','):
        calls.append(int(i))
       
a = np.loadtxt(file, dtype = int, skiprows = 1)
n = np.shape(a)[0]//5
boards = np.reshape(a, (n,5,5))
rows = np.zeros((n,5), dtype = int)
cols = np.zeros((n,5), dtype = int)
rolling_sum = np.zeros((n), dtype = int)

for call in calls:
        locs = np.nonzero(boards == call)
        rows[locs[0],locs[1]] +=1
        cols[locs[0], locs[2]] +=1
        if np.amax(rows) < 5 and np.amax(cols) < 5:
            lastwinner = np.unravel_index(rows.argmax(), rows.shape)[0]
            print(lastwinner)

rows = np.zeros((n,5), dtype = int)
cols = np.zeros((n,5), dtype = int)
            
for call in calls:
        locs = np.nonzero(boards == call)
        rolling_sum[locs[0]] += call
        print(rolling_sum[lastwinner])
        rows[locs[0],locs[1]] +=1
        cols[locs[0], locs[2]] +=1
        if np.amax(rows[lastwinner]) == 5:
            winner =np.unravel_index(rows.argmax(), rows.shape)[0]
            print("fin rows")
            break
        if np.amax(cols[lastwinner]) == 5:
            winner =np.unravel_index(cols.argmax(), cols.shape)[0]
            print("fin cols")
            break
            
print(boards[lastwinner])
print(boards[lastwinner].sum())


print()
board_score = boards[lastwinner].sum()-rolling_sum[lastwinner]
print("board score", board_score)
# print("last call", call)
# print("score", board_score * call)

0
0
56
17
56
56
56
56
56
17
17
15
92
92
92
38
38
38
38
38
14
44
44
52
52
52
52
52
52
52
52
90
90
90
90
102
102
102
156
156
156
156
156
156
156
209
233
233
293
293
293
293
293
293
358
392
392
392
434
434
434
434
434
434
465
465
494
494
494
494
494
494
533
533
539
539
539
539
539
539
539
618
fin rows
[[53 24 29 60 79]
 [57 39 31 34 15]
 [12 38 13  8 30]
 [94 98 14 54  6]
 [47 82 65 22 42]]
1046

board score 428
